name: 'data_pipeline_observability'
version: '1.0.0'
config-version: 2

profile: 'data_pipeline_observability'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  data_pipeline_observability:
    staging:
      +materialized: view
    marts:
      +materialized: table

on-run-end:
  - "{{ check_untested_models() }}"
